# theme: minima
remote_theme: jekyll/minima@38a84a949f9753c4542e25f422935f59b4913053
title: uosjead
# description: footer
# exclude: ["README.md"]


# About/contact
author: ""

github_username:  uosjead
linkedin_username: uosjead

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/uosjead", github_username: github }
    - { platform: linkedin, user_url: "https://linkedin.com", linkedin_username: linkedin }
    - { platform: stackoverflow,  user_url: "https://stackoverflow.com/" }
    
include:
  - _includes
