theme: minima
title: uosjead
# description: footer
# exclude: ["README.md"]


# About/contact
author: wp

github_username:  uosjead
linkedin_username: uosjead

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/uosjead" }
    - { platform: linkedin, user_url: "https://linkedin.com" }
    - { platform: stackoverflow,  user_url: "https://stackoverflow.com/" }
    
include:
  - _includes
