# theme: minima
remote_theme: jekyll/minima@2863624b903b17f838d6ce8d2f77900fa9d3c864
title: uosjead
description: ""
# exclude: ["README.md"]



url: "https://uosjead.me"
plugins:
  - jekyll-sitemap
#   - jekyll-feed

# About/contact
# author:
#   name: ""
#   email: ""

author: wp

github_username:  uosjead
linkedin_username: uosjead

minima:
  # skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/uosjead" }
    - { platform: linkedin, user_url: "https://linkedin.com/in/uosjead" }

#     - { platform: stackoverflow,  user_url: "https://stackoverflow.com/" }


header_pages:
  - typing-game.html
  - about.md

include:
  - _includes
